const SubjectData = [
  {
    id: 1,
    title: 'Science',
    description: 'Explore the world of science!',
    iconPath: '',
    color: '#BDEE77',
    isUnlocked: true,
  },
  {
    id: 2,
    title: 'Biology',
    description: 'Discover the secrets of living organisms!',
    iconPath: '',
    color: '#BDEE77',
    isUnlocked: false,
  },
  {
    id: 3,
    title: 'Environment',
    description: 'Learn about nature and conservation!',
    iconPath: '',
    color: '#BDEE77',
    isUnlocked: true,
  },
  {
    id: 4,
    title: 'English',
    description: 'Enhance your language and communication!',
    iconPath: '',
    color: '#A1D8E4',
    isUnlocked: true,
  },
  {
    id: 5,
    title: 'Coding',
    description: 'Create and build with computer programming!',
    iconPath: '',
    color: '#A1D8E4',
    isUnlocked: true,
  },
  {
    id: 6,
    title: 'Math',
    description: 'Master numbers and problem-solving!',
    iconPath: '',
    color: '#C792C8',
    isUnlocked: true,
  },
  {
    id: 7,
    title: 'Money',
    description: 'Understand the value of currency!',
    iconPath: '',
    color: '#C792C8',
    isUnlocked: true,
  },
  {
    id: 8,
    title: 'Music',
    description: 'Harmonize with melodies and rhythms!',
    iconPath: '',
    color: '#C792C8',
    isUnlocked: true,
  },
  {
    id: 9,
    title: 'Social Study',
    description: 'Journey through history and society!',
    iconPath: '',
    color: '#ECC283',
    isUnlocked: true,
  },
  {
    id: 10,
    title: 'Languages',
    description: 'Speak and understand diverse cultures!',
    iconPath: '',
    color: '#ECC283',
    isUnlocked: true,
  },
  {
    id: 11,
    title: 'Logic',
    description: 'Analyze and solve complex problems!',
    iconPath: '',
    color: '#FC99CE',
    isUnlocked: true,
  },
  {
    id: 12,
    title: 'Life Skills',
    description: 'Develop essential practical abilities!',
    iconPath: '',
    color: '#FC99CE',
    isUnlocked: true,
  },
  {
    id: 13,
    title: 'Emotions',
    description: 'Understand and express your feelings!',
    iconPath: '',
    color: '#FC99CE',
    isUnlocked: true,
  },
  {
    id: 14,
    title: 'Innovation',
    description: 'Ignite your creativity and business ideas!',
    iconPath: '',
    color: '#FC99CE',
    isUnlocked: true,
  },
];

const SubjectDetailData = [
  {
    id: 1,
    title: 'Animals and Their Habitats',
  },
  {
    id: 2,
    title: 'Plants and Photosynthesis',
  },
  {
    id: 3,
    title: 'Scientific Method and Experiments',
  },
  {
    id: 4,
    title: 'Animals and Their Habitats',
  },
  {
    id: 5,
    title: 'Weather and Climate',
  },
];

export { SubjectData, SubjectDetailData };
