import AddChildrenScreen from './addChildren/AddChildrenScreen';
import PersonalityTestsScreen from './personalityTests/PersonalityTestsScreen';
import BigFivePersonalityTestIntroScreen from './bigFivePersonalityTest/BigFivePersonalityTestIntroScreen';
import BigFivePersonalityTestQuestionsScreen from './bigFivePersonalityTest/BigFivePersonalityTestQuestionsScreen';
import BigFivePersonalityTestResultScreen from './bigFivePersonalityTest/BigFivePersonalityTestResultScreen';
import EmotionalIntelligenceTestIntroScreen from './emotionalIntelligenceTest/EmotionalIntelligenceTestIntroScreen';
import EmotionalIntelligenceTestQuestionsScreen from './emotionalIntelligenceTest/EmotionalIntelligenceTestQuestionsScreen';
import EmotionalIntelligenceTestResultScreen from './emotionalIntelligenceTest/EmotionalIntelligenceTestResultScreen';
import ConflictResolutionStyleTestIntroScreen from './conflictResolutionStyleTest/ConflictResolutionStyleTestIntroScreen';
import ConflictResolutionStyleTestQuestionsScreen from './conflictResolutionStyleTest/ConflictResolutionStyleTestQuestionsScreen';
import ConflictResolutionStyleTestResultScreen from './conflictResolutionStyleTest/ConflictResolutionStyleTestResultScreen';
import ValuesAssessmentTestIntroScreen from './valuesAssessmentTest/ValuesAssessmentTestIntroScreen';
import ValuesAssessmentTestQuestionsScreen from './valuesAssessmentTest/ValuesAssessmentTestQuestionsScreen';
import ValuesAssessmentTestResultScreen from './valuesAssessmentTest/ValuesAssessmentTestResultScreen';

export {
  AddChildrenScreen,
  PersonalityTestsScreen,
  BigFivePersonalityTestIntroScreen,
  BigFivePersonalityTestQuestionsScreen,
  BigFivePersonalityTestResultScreen,
  EmotionalIntelligenceTestIntroScreen,
  EmotionalIntelligenceTestQuestionsScreen,
  EmotionalIntelligenceTestResultScreen,
  ConflictResolutionStyleTestIntroScreen,
  ConflictResolutionStyleTestQuestionsScreen,
  ConflictResolutionStyleTestResultScreen,
  ValuesAssessmentTestIntroScreen,
  ValuesAssessmentTestQuestionsScreen,
  ValuesAssessmentTestResultScreen,
};
