export const ASSETS = {
  LOGO: '/assets/images/logo.png',
  VOLUME:"/assets/images/voice/volume.png",
  ADDCIRCLE:"/assets/images/voice/add-circle 2.png",
  EDITVOICE:"/assets/images/voice/edit.png",
  DELETEVOICE:"/assets/images/voice/bin.png",
  POPUPCLOSE:"/assets/images/voice/closePopup.png",
  RECORDVOICE:"/assets/images/voice/record.png",
  UPLOADVOICE:"/assets/images/voice/uplaodvoice.png",
  DELETEPOPUPVOICE:"/assets/images/voice/delrecord.png",
  SAVEVOICE:"/assets/images/voice/save.png",
  AUTHENTICATION: {
    MAIN_BACKGROUND: '/assets/images/authentication/main-background.png',
    ICONS: {
      GOOGLE: '/assets/images/authentication/google.svg',
      FACEBOOK: '/assets/images/authentication/facebook.svg',
      CONFIRMATION_LIKE: '/assets/images/authentication/confirmation-like.svg',
    },
  },
  ON_BOARDING: {
    CHILD: '/assets/images/on-boarding/child.png',
  },
  PARENT: {
    ICONS: {
      DASHBOARD: '/assets/images/parent/dashboard.svg',
      PERFORMANCE: '/assets/images/parent/performance.svg',
      LEARN_SUBJECT: '/assets/images/parent/learn-subject.svg',
      DAILY_QUIZ: '/assets/images/parent/daily-quiz.svg',
      IMPROVE_PARENTING: '/assets/images/parent/improve-parenting.svg',
      EXPLORE: '/assets/images/parent/explore.svg',
      JOURNAL: '/assets/images/parent/journal.svg',
      SETTINGS: '/assets/images/parent/settings.svg',
      LOGOUT: '/assets/images/parent/logout.svg',
    },
    DASHBOARD: {},
  },
  PLACEHOLDER: {
    CHILD: '/assets/images/on-boarding/child.png',
  },
  SUBJECTS: {
    SCIENCE: '/assets/icons/science.svg',
    BIOLOGY: '/assets/icons/biology.svg',
    ENVIRONMENT: '/assets/icons/environment.svg',
    ENGLISH: '/assets/icons/english.svg',
    MATH: '/assets/icons/math.svg',
    MONEY: '/assets/icons/money.svg',
    MUSIC: '/assets/icons/music.svg',
    SOCIAL_STUDY: '/assets/icons/social-study.svg',
    LOGIC: '/assets/icons/logic.svg',
    LIFE_SKILLS: '/assets/icons/life-skills.svg',
    EMOTIONS: '/assets/icons/emotions.svg',
    INNOVATION: '/assets/icons/innovation.svg',
    CODING: '/assets/icons/coding.svg',
    LANGUAGES: '/assets/icons/languages.svg',
  },
  CHAT: {
    CHAT_BOT_ICON: '/assets/icons/CHATBOT.svg',
  },
};
