const SubjectDetails = {
  summary:
    'Your child has demonstrated a basic understanding of the subject matter in all areas. They meet minimum expectations, but there are areas that could benefit from improvement. Encourage them to continue working hard!',
  percentage: 73.5,
  topics: [
    { title: 'Measurement & Data', percentage: 76 },
    { title: 'Problem solving & Logic', percentage: 49 },
    { title: 'Geometry & Shapes', percentage: 81 },
    { title: 'Fractions & Decimals', percentage: 81 },
    { title: 'Addition & Subtraction', percentage: 94 },
    { title: 'Multiplication & Devision', percentage: -1 },
    { title: 'Measurement & Data', percentage: 76 },
    { title: 'Problem Solving & Logic', percentage: 49 },
    { title: 'Geometry & Shapes', percentage: 81 },
  ],
};

const SubjectData = [
  {
    id: 1,
    title: 'Science',
    description: 'Explore the wonders of the world!',
    color: '#BDEE77',
    iconPath: '/assets/icons/science.svg',
    grade: 'A+',
    details: SubjectDetails,
  },
  {
    id: 2,
    title: 'Biology',
    description: 'Discover the secrets of living organisms!',
    color: '#BDEE77',
    iconPath: '/assets/icons/biology.svg',
    grade: 'B-',
    details: SubjectDetails,
  },
  {
    id: 3,
    title: 'Environment',
    description: 'Learn about nature and conservation!',
    color: '#BDEE77',
    iconPath: '/assets/icons/environment.svg',
    grade: 'C',
    details: SubjectDetails,
  },
  {
    id: 4,
    title: 'English',
    description: 'Enhance your language and communication!',
    color: '#A1D8E4',
    iconPath: '/assets/icons/english.svg',
    grade: 'C',
    details: SubjectDetails,
  },
  {
    id: 5,
    title: 'Math',
    description: 'Master numbers and problem-solving!',
    color: '#C792C8',
    iconPath: '/assets/icons/english.svg',
    grade: 'A+',
    details: SubjectDetails,
  },
  {
    id: 6,
    title: 'Money',
    description: 'Understand the value of currency!',
    color: '#C792C8',
    iconPath: '/assets/icons/english.svg',
    grade: 'C',
    details: SubjectDetails,
  },
  {
    id: 7,
    title: 'Music',
    description: 'Harmonize with melodies and rhythms!',
    color: '#C792C8',
    iconPath: '/assets/icons/english.svg',
    grade: 'C+',
    details: SubjectDetails,
  },
  {
    id: 8,
    title: 'Social Study',
    description: 'Journey through history and society!',
    color: '#ECC283',
    iconPath: '/assets/icons/english.svg',
    grade: 'B+',
    details: SubjectDetails,
  },
  {
    id: 9,
    title: 'Logic',
    description: 'Analyze and solve complex problems!',
    color: '#FC99CE',
    iconPath: '/assets/icons/english.svg',
    grade: 'B-',
    details: SubjectDetails,
  },
  {
    id: 10,
    title: 'Life Skills',
    description: 'Develop essential practical abilities!',
    color: '#FC99CE',
    iconPath: '/assets/icons/english.svg',
    grade: 'A+',
    details: SubjectDetails,
  },
  {
    id: 11,
    title: 'Emotions',
    description: 'Understand and express your feelings!',
    color: '#FC99CE',
    iconPath: '/assets/icons/english.svg',
    grade: 'C',
    details: SubjectDetails,
  },
  {
    id: 12,
    title: 'Innovation',
    description: 'Ignite your creativity and business ideas!',
    color: '#FC99CE',
    iconPath: '/assets/icons/english.svg',
    grade: 'A',
    details: SubjectDetails,
  },
];

const StrengthsData = [
  {
    id: 1,
    subject: 'Science',
    topic: 'Earth and Space',
    grade: 'A+',
    color: '#BDEE77',
    iconPath: '/assets/icons/science.svg',
  },
  {
    id: 2,
    subject: 'Biology',
    topic: 'Weather and Climate',
    grade: 'B-',
    color: '#BDEE77',
    iconPath: '/assets/icons/biology.svg',
  },
  {
    id: 3,
    subject: 'English',
    topic: 'Drama and Performance',
    grade: 'C',
    color: '#A1D8E4',
    iconPath: '/assets/icons/english.svg',
  },
  {
    id: 4,
    subject: 'Math',
    topic: 'Problem Solving',
    grade: 'C',
    color: '#C792C8',
    iconPath: '/assets/icons/english.svg',
  },
  {
    id: 5,
    subject: 'Math',
    topic: 'Geometry and Shapes',
    grade: 'A+',
    color: '#C792C8',
    iconPath: '/assets/icons/english.svg',
  },
  {
    id: 6,
    subject: 'Math',
    topic: 'Fractions and Decimals',
    grade: 'C',
    color: '#C792C8',
    iconPath: '/assets/icons/english.svg',
  },
  {
    id: 7,
    subject: 'Math',
    topic: 'Addition and Substraction',
    grade: 'C+',
    color: '#C792C8',
    iconPath: '/assets/icons/english.svg',
  },
  {
    id: 8,
    subject: 'Innovation',
    topic: 'Business Ideas',
    grade: 'B+',
    color: '#ECC283',
    iconPath: '/assets/icons/english.svg',
  },
  {
    id: 9,
    subject: 'Innovation',
    topic: 'Fostering Creativity',
    grade: 'B-',
    color: '#FC99CE',
    iconPath: '/assets/icons/english.svg',
  },
  {
    id: 10,
    subject: 'Logic',
    topic: 'Induction',
    grade: 'A+',
    color: '#FC99CE',
    iconPath: '/assets/icons/english.svg',
  },
  {
    id: 11,
    subject: 'Emotions',
    topic: 'Happy Empathy',
    grade: 'C',
    color: '#FC99CE',
    iconPath: '/assets/icons/english.svg',
  },
  {
    id: 12,
    subject: 'Emotions',
    topic: 'Easing Stress',
    color: '#FC99CE',
    iconPath: '/assets/icons/english.svg',
  },
  {
    id: 13,
    subject: 'Emotions',
    topic: 'Happy Empathy',
    grade: 'C',
    color: '#FC99CE',
    iconPath: '/assets/icons/english.svg',
  },
  {
    id: 14,
    subject: 'Emotions',
    topic: 'Easing Stress',
    color: '#FC99CE',
    iconPath: '/assets/icons/english.svg',
  },
];

const OverallScoreData = {
  graph: [
    { id: '1', label: 'A', color: '#BDEE77', value: 47 },
    { id: '2', label: 'B', color: '#ECC283', value: 18 },
    { id: '3', label: 'B', color: '#A1D8E4', value: 16 },
    { id: '4', label: 'C', color: '#FC99CE', value: 10 },
    { id: '5', label: 'C+', color: '#C792C8', value: 14 },
  ],
  grade: 'B-',
  summary:
    'Your child has demonstrated a basic understanding of the subject matter in all areas. They meet minimum expectations, but there are areas that could benefit from improvement. Encourage them to continue working hard!',
  legend: [
    { label: 'Science, biology, & Environment', color: '#BDEE77' },
    { label: 'English & Coding', color: '#ECC283' },
    { label: 'Math, Money, & Music', color: '#A1D8E4' },
    { label: 'Social Study & Languages', color: '#FC99CE' },
    { label: 'Logic, Life Skills, Emotions, & Innovation', color: '#C792C8' },
  ],
};

export { SubjectData, StrengthsData, OverallScoreData };
